apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector:
    matchLabels:
      statefulset.kubernetes.io/pod-name: cassandra-2
  policyTypes:
  - Ingress
  - Egress